# -*- coding: utf-8 -*-
"""DAY-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DDRreiMRzG_cVq6IMBcHfHMN5P-pASgD
"""

# Creating a List
my_list = [10, 20, 30, 40, 50]
print("List:", my_list)

# Accessing elements by index
print("Accessing list element at index 2:", my_list[2])
print("Accessing list element at index -1 (last element):", my_list[-1])
print("Accessing list elements by using ':' :", my_list[:])

# Creating a Tuple
my_tuple = (5, 10, 15, 20, 25)
print("Tuple:", my_tuple)

# Accessing elements by index
print("Accessing tuple element at index 1:", my_tuple[1])
print("Accessing tuple element at index -3:", my_tuple[-3])

# Creating a Dictionary
my_dict = {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 500}
print("Dictionary:", my_dict)

# Accessing elements by using keys in dictionary
print("Accessing dictionary element with key 'b':", my_dict['b'])
print("Accessing dictionary element with key 'e':", my_dict['e'])