# -*- coding: utf-8 -*-
"""DAY-1 Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KwXr1HwRi62y726ffxZCWvCXoajrIbim
"""

#Write a program in Jupyter Notebook to declare variables of different data types (integer, float, string, and boolean). Print each variable and its type.
# Declare variables of different data types
integer_var = 42
float_var = 3.14
string_var = "Hello, World!"
boolean_var = True

# Printing each variable and its type
print("Integer Variable:", integer_var, "| Type:", type(integer_var))
print("Float Variable:", float_var, "| Type:", type(float_var))
print("String Variable:", string_var, "| Type:", type(string_var))
print("Boolean Variable:", boolean_var, "| Type:", type(boolean_var))